steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "build", "-t", "gcr.io/$PROJECT_ID/ngipen-backend:$COMMIT_SHA", "." ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/ngipen-backend" ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
       [
         "run",
         "deploy",
         "ngipen-backend",
         "--image",
         "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA",
         "--region",
         "global",
         "--platform",
         "managed",
         "--allow-unauthenticated",
       ]