steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [ "build", "-t", "gcr.io/$PROJECT_ID/github.com/rjial/ngipen-backend:${SHORT_SHA}", "." ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/$PROJECT_ID/github.com/rjial/ngipen-backend" ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
       [
         "run",
         "deploy",
         "$_SERVICE_NAME",
         "--image",
         "gcr.io/$PROJECT_ID/$_SERVICE_NAME:${SHORT_SHA}",
         "--region",
         "global",
         "--platform",
         "managed",
         "--allow-unauthenticated",
       ]